#!/usr/bin/env Rscript
# ============================================================
# PRISMA Meta-Analysis Script Template
# Generated by: Hermes Agent PRISMA Pipeline
# Package: metafor (Viechtbauer, 2010)
# ============================================================

# --- Install Dependencies ---
required_pkgs <- c("metafor", "ggplot2", "dplyr", "readr", "forestploter")
for (pkg in required_pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, repos = "https://cloud.r-project.org")
  }
}

library(metafor)
library(ggplot2)
library(dplyr)
library(readr)

# ============================================================
# 1. CONFIGURATION — MODIFY THESE FOR YOUR REVIEW
# ============================================================

# Input data file (CSV from data extraction)
DATA_FILE <- "extracted_data.csv"

# Effect measure: "OR" (odds ratio), "RR" (risk ratio), "SMD" (standardized mean diff),
# "HR" (hazard ratio), "MD" (mean difference)
EFFECT_MEASURE <- "OR"

# Transform effect sizes? TRUE if using log-scale measures (OR, RR, HR)
LOG_TRANSFORM <- TRUE

# Meta-analysis model: "REML" (recommended), "DL", "FE", "PM"
MODEL_METHOD <- "REML"

# Confidence level
CI_LEVEL <- 95

# Output prefix
OUTPUT_PREFIX <- "meta_analysis"

# ============================================================
# 2. LOAD AND PREPARE DATA
# ============================================================

cat("Loading data from:", DATA_FILE, "\n")

# Expected CSV columns:
# study_id    - Unique study identifier
# author      - First author surname
# year        - Publication year
# effect_size - Raw effect size (OR, RR, SMD, etc.)
# se          - Standard error
# ci_lower    - Lower 95% CI bound
# ci_upper    - Upper 95% CI bound
# n_total     - Total sample size
# n_treatment - Treatment/exposure group n
# n_control   - Control/comparator group n
# events_treatment - Events in treatment group (for binary outcomes)
# events_control   - Events in control group (for binary outcomes)

data <- read.csv(DATA_FILE, stringsAsFactors = FALSE)

cat("Studies loaded:", nrow(data), "\n")
cat("Columns:", paste(names(data), collapse = ", "), "\n")

# If data has raw counts but not pre-computed effect sizes, compute them:
# (Uncomment the appropriate block below)

# --- FOR BINARY OUTCOMES (2x2 tables) ---
# data <- escalc(
#   measure = EFFECT_MEASURE,
#   ai = events_treatment,
#   n1i = n_treatment,
#   ci = events_control,
#   n2i = n_control,
#   data = data
# )
# # yi = log effect size, vi = variance
# data$effect_size <- data$yi
# data$se <- sqrt(data$vi)

# --- FOR CONTINUOUS OUTCOMES ---
# data <- escalc(
#   measure = "SMD",
#   m1i = mean_treatment, sd1i = sd_treatment, n1i = n_treatment,
#   m2i = mean_control,   sd2i = sd_control,   n2i = n_control,
#   data = data
# )
# data$effect_size <- data$yi
# data$se <- sqrt(data$vi)

# ============================================================
# 3. RANDOM-EFFECTS META-ANALYSIS
# ============================================================

cat("\n========================================\n")
cat("RANDOM-EFFECTS META-ANALYSIS\n")
cat("Model:", MODEL_METHOD, "| Measure:", EFFECT_MEASURE, "\n")
cat("========================================\n\n")

meta_result <- rma(
  yi     = effect_size,
  sei    = se,
  data   = data,
  method = MODEL_METHOD,
  level  = CI_LEVEL,
  slab   = paste(data$author, data$year, sep = ", ")
)

# Print summary
summary(meta_result)

# ============================================================
# 4. HETEROGENEITY STATISTICS
# ============================================================

cat("\n========================================\n")
cat("HETEROGENEITY ASSESSMENT\n")
cat("========================================\n")
cat("Cochran's Q      :", round(meta_result$QE, 3), "\n")
cat("Q p-value        :", format(meta_result$QEp, scientific = TRUE), "\n")
cat("I-squared        :", round(meta_result$I2, 1), "%\n")
cat("Tau-squared      :", round(meta_result$tau2, 4), "\n")
cat("Tau (SD)         :", round(sqrt(meta_result$tau2), 4), "\n")
cat("H-squared        :", round(meta_result$H2, 2), "\n")

# Interpret I-squared
i2 <- meta_result$I2
i2_label <- ifelse(i2 < 25, "low",
                   ifelse(i2 < 50, "moderate",
                          ifelse(i2 < 75, "substantial", "considerable")))
cat("Interpretation   :", i2_label, "heterogeneity\n")

# ============================================================
# 5. POOLED EFFECT ESTIMATE
# ============================================================

cat("\n========================================\n")
cat("POOLED EFFECT ESTIMATE\n")
cat("========================================\n")

if (LOG_TRANSFORM) {
  # Back-transform from log scale
  pooled <- exp(coef(meta_result))
  ci_lb  <- exp(meta_result$ci.lb)
  ci_ub  <- exp(meta_result$ci.ub)
  cat("Pooled", EFFECT_MEASURE, ":", round(pooled, 3), "\n")
  cat("95% CI             :", round(ci_lb, 3), "-", round(ci_ub, 3), "\n")
} else {
  pooled <- coef(meta_result)
  ci_lb  <- meta_result$ci.lb
  ci_ub  <- meta_result$ci.ub
  cat("Pooled estimate    :", round(pooled, 3), "\n")
  cat("95% CI             :", round(ci_lb, 3), "-", round(ci_ub, 3), "\n")
}

cat("P-value            :", format(meta_result$pval, scientific = TRUE), "\n")
cat("Studies included   :", meta_result$k, "\n")

# ============================================================
# 6. FOREST PLOT
# ============================================================

forest_file <- paste0(OUTPUT_PREFIX, "_forest.png")
png(forest_file, width = 1400, height = max(600, 200 + meta_result$k * 40), res = 150)

forest(meta_result,
       xlab    = paste0("Effect Size (", EFFECT_MEASURE, ", 95% CI)"),
       main    = "Forest Plot: Random-Effects Meta-Analysis",
       cex     = 0.8,
       col     = "darkblue",
       border  = "darkblue",
       refline = ifelse(LOG_TRANSFORM, 1, 0),
       header  = c("Study", paste0(EFFECT_MEASURE, " [95% CI]")))

dev.off()
cat("\nForest plot saved:", forest_file, "\n")

# ============================================================
# 7. FUNNEL PLOT (Publication Bias Visual)
# ============================================================

funnel_file <- paste0(OUTPUT_PREFIX, "_funnel.png")
png(funnel_file, width = 900, height = 700, res = 150)

funnel(meta_result,
       main  = "Funnel Plot: Publication Bias Assessment",
       xlab  = paste0("Effect Size (", EFFECT_MEASURE, ")"),
       level = c(90, 95, 99),
       shade = c("white", "gray75", "gray90"),
       refline = 0)

dev.off()
cat("Funnel plot saved:", funnel_file, "\n")

# ============================================================
# 8. STATISTICAL TESTS FOR PUBLICATION BIAS
# ============================================================

cat("\n========================================\n")
cat("PUBLICATION BIAS TESTS\n")
cat("========================================\n")

# Egger's regression test
if (meta_result$k >= 3) {
  egger <- regtest(meta_result, model = "lm")
  cat("Egger's test:\n")
  cat("  Test statistic  :", round(egger$zval, 3), "\n")
  cat("  P-value         :", round(egger$pval, 4), "\n")
  cat("  Interpretation  :",
      ifelse(egger$pval < 0.05,
             "Significant asymmetry — possible publication bias",
             "No significant asymmetry detected"), "\n")
} else {
  cat("Egger's test: Not enough studies (k < 3)\n")
}

# Begg's rank correlation test
if (meta_result$k >= 3) {
  begg <- ranktest(meta_result)
  cat("\nBegg's rank test:\n")
  cat("  Kendall's tau   :", round(begg$tau, 3), "\n")
  cat("  P-value         :", round(begg$pval, 4), "\n")
}

# Trim-and-fill analysis
if (meta_result$k >= 3) {
  cat("\nTrim-and-fill analysis:\n")
  tf <- trimfill(meta_result)
  summary(tf)
  cat("  Imputed studies :", tf$k0, "\n")
  if (LOG_TRANSFORM) {
    cat("  Adjusted pooled :", round(exp(coef(tf)), 3), "\n")
  } else {
    cat("  Adjusted pooled :", round(coef(tf), 3), "\n")
  }
}

# ============================================================
# 9. SENSITIVITY ANALYSIS (Leave-one-out)
# ============================================================

cat("\n========================================\n")
cat("SENSITIVITY ANALYSIS (Leave-One-Out)\n")
cat("========================================\n")

sensitivity <- leave1out(meta_result)
sens_file <- paste0(OUTPUT_PREFIX, "_sensitivity.csv")
write.csv(sensitivity, sens_file, row.names = FALSE)
cat("Sensitivity results saved:", sens_file, "\n")

# Check if any single study unduly influences results
max_influence <- max(abs(sensitivity$estimate - coef(meta_result)))
cat("Maximum single-study influence:", round(max_influence, 4), "\n")
cat("Interpretation:",
    ifelse(max_influence > 0.5,
           "WARNING: At least one study has substantial influence",
           "No single study appears to unduly drive results"), "\n")

# ============================================================
# 10. SUBGROUP ANALYSIS TEMPLATE
# ============================================================

# Uncomment and modify for subgroup analyses:
#
# --- By study design ---
# meta_subgroup <- rma(yi = effect_size, sei = se,
#                       data = data, method = MODEL_METHOD,
#                       mods = ~ factor(study_design) - 1)
# summary(meta_subgroup)
#
# --- By geographic region ---
# meta_region <- rma(yi = effect_size, sei = se,
#                     data = data, method = MODEL_METHOD,
#                     mods = ~ factor(region) - 1)
# summary(meta_region)
#
# --- By follow-up duration ---
# meta_duration <- rma(yi = effect_size, sei = se,
#                       data = data, method = MODEL_METHOD,
#                       mods = ~ follow_up_months)
# summary(meta_duration)
#
# --- Meta-regression ---
# meta_regression <- rma(yi = effect_size, sei = se,
#                         data = data, method = MODEL_METHOD,
#                         mods = ~ year + sample_size)
# summary(meta_regression)

# ============================================================
# 11. CUMULATIVE META-ANALYSIS (by year)
# ============================================================

cat("\n========================================\n")
cat("CUMULATIVE META-ANALYSIS (by year)\n")
cat("========================================\n")

cumulative <- cumul(meta_result, order = order(data$year))
cum_file <- paste0(OUTPUT_PREFIX, "_cumulative.csv")
write.csv(
  data.frame(
    year = data$year[order(data$year)],
    estimate = cumulative$estimate,
    ci_lb = cumulative$ci.lb,
    ci_ub = cumulative$ci.ub,
    pval = cumulative$pval
  ),
  cum_file, row.names = FALSE
)
cat("Cumulative analysis saved:", cum_file, "\n")

# ============================================================
# 12. FINAL SUMMARY TABLE
# ============================================================

cat("\n========================================\n")
cat("FINAL SUMMARY\n")
cat("========================================\n")
cat("Studies included     :", meta_result$k, "\n")
cat("Total participants   :", sum(data$n_total, na.rm = TRUE), "\n")
cat("Pooled effect (", EFFECT_MEASURE, ") :", round(pooled, 3), "\n")
cat("95% CI               :", round(ci_lb, 3), "-", round(ci_ub, 3), "\n")
cat("P-value              :", format(meta_result$pval, scientific = TRUE), "\n")
cat("I-squared            :", round(meta_result$I2, 1), "% (", i2_label, ")\n")
cat("Tau-squared          :", round(meta_result$tau2, 4), "\n")

cat("\n========================================\n")
cat("ALL OUTPUT FILES\n")
cat("========================================\n")
cat("1.", forest_file, "- Forest plot\n")
cat("2.", funnel_file, "- Funnel plot\n")
cat("3.", sens_file, "- Leave-one-out sensitivity\n")
cat("4.", cum_file, "- Cumulative meta-analysis\n")
cat("\nDone.\n")
